---

- name: Query current profile
  ansible.builtin.command: eselect --brief --color=no profile show
  check_mode: no
  changed_when: False
  register: gentoo_portage__register_profile

- name: Query available profiles
  ansible.builtin.command: eselect --brief profile list
  check_mode: no
  changed_when: False
  register: gentoo_portage__register_profile_list
  when: not gentoo_portage__register_profile.stdout.strip() == gentoo_portage__profile

- name: Set profile
  ansible.builtin.command: 'eselect profile set {{ gentoo_portage__profile }}'
  when:
    - not gentoo_portage__register_profile_list is skipped
    - gentoo_portage__profile in gentoo_portage__register_profile_list.stdout_lines
