---

- name: Create eix database directory
  ansible.builtin.file:
    path: '/var/cache/eix'
    state: directory
    owner: 'portage'
    group: 'portage'
    mode: '0755'

- name: Check if eix database exists
  ansible.builtin.stat:
    path: '/var/cache/eix/portage.eix'
  register: gentoo_portage__register_eix_database

- name: Create eix database
  ansible.builtin.command: eix-update  # noqa no-changed-when
  when: not gentoo_portage__register_eix_database.stat.exists
